opam-version: "2.0"
maintainer: "gaetan.gilbert@skyskimmer.net"
version: "v9.0-lean3+alpha"

homepage: "https://github.com/SkySkimmer/coq-lean-import"
dev-repo: "git+https://github.com/SkySkimmer/coq-lean-import.git"
bug-reports: "https://github.com/SkySkimmer/coq-lean-import/issues"
license: "LGPL-2.1-only"

synopsis: "Plugin allowing Coq to import Lean exported files"
description: """
Plugin allowing Coq to import Lean exported files."""

build: [make "-j%{jobs}%" "test"]
install: [make "install"]
depends: [
  "ocaml" {>= "4.09.0"}
  "rocq-core" {(>= "9.0~" & < "9.1") | (= "dev")}
]

tags: [
  "logpath:LeanImport"
]
authors: [
  "Gaëtan Gilbert"
]
